import * as fs from 'node:fs';
import * as path from 'node:path';

const root = path.resolve(__dirname, '..');
const entryFile = path.join(root, 'preload.js');
const moduleFiles = {
  entry: entryFile,
  api: path.join(root, 'preload', 'api.js'),
  chrome: path.join(root, 'preload', 'chrome.js'),
} as const;

function readCompiled(file: string): string {
  if (!fs.existsSync(file)) throw new Error(`bundle-preload: compiled module is missing: ${file}`);
  return fs.readFileSync(file, 'utf8');
}

const modules = Object.entries(moduleFiles)
  .map(([id, file]) => {
    const source = readCompiled(file);
    return `${JSON.stringify(id)}: function (module, exports, require) {\n${source}\n}`;
  })
  .join(',\n');

const bundle = `'use strict';
// Generated by scripts/bundle-preload.ts. Sandboxed Electron preloads cannot
// resolve local modules, so keep the strict-TS source split but emit one file.
const __dshNativeRequire = require;
const __dshPreloadModules = {
${modules}
};
const __dshPreloadCache = Object.create(null);
function __dshPreloadLoad(id) {
  if (__dshPreloadCache[id]) return __dshPreloadCache[id].exports;
  const factory = __dshPreloadModules[id];
  if (!factory) throw new Error('Unknown bundled preload module: ' + id);
  const module = { exports: {} };
  __dshPreloadCache[id] = module;
  const localRequire = (specifier) => {
    if (specifier === 'electron') return __dshNativeRequire('electron');
    if (specifier === './preload/api.js') return __dshPreloadLoad('api');
    if (specifier === './preload/chrome.js') return __dshPreloadLoad('chrome');
    throw new Error('Unsupported bundled preload dependency: ' + specifier);
  };
  factory(module, module.exports, localRequire);
  return module.exports;
}
__dshPreloadLoad('entry');
`;

fs.writeFileSync(entryFile, bundle);
console.log('bundle-preload: emitted sandbox-safe preload.js');
